src/Mess/Controllers/CacheController.cs
using Mess.Models;
using Microsoft.AspNetCore.Mvc;

namespace Mess.Controllers
{
public class CacheController : Controller
{
    public CacheController(MemoryDb db) {
        this.db = db;
    }
    MemoryDb db = null;

    public IActionResult Index(bool populate = false, int removeId = 0, int updateId = 0) {
        if (populate)
            new PopulateDatabase(db).Execute();
        if (removeId > 0)
            db.Delete<Post>(removeId);
        if (updateId > 0) {
            var item = db.Select<Post>(updateId);
            item.Title = "Updated";
            db.Update<Post>(item);
        }
        return View(db.Select<Post>());
    }

    public void AddPost(Post post) {
        db.Insert(post);
    }
}
}

src/Mess/Views/Cache/index.cshtml
@model List<Post>
@{ ViewData["Title"] = "Posts"; }
<h1>Posts</h1>
<ul>
@foreach (var post in @Model) {
    <li>
        @post.Id @post.Title
    </li>
}
</ul>
<h2>Populate</h2>
<p>
    @Html.ActionLink("Populate", "Index", "Cache", new { populate = true }, new {})
</p>

<h2>Update</h2>
<p>
    @Html.TextBox("UpdateId")
    @Html.ActionLink("Update", "Index", "Cache", new { updateId = 1 }, new {})
</p>

<h2>Remove</h2>
<p>
    @Html.TextBox("RemoveId")
    <a href="javascript:void(0)" onclick="onRemove()">Remove</a>
</p>

<script>
    function onRemove() {
        var id = document.getElementById('RemoveId').value
        remove(id)
        window.location = '/cache'
    }
    function remove(id) {
        var ajax = new XMLHttpRequest()
        ajax.open("GET", "cache?removeId="+id, true)
        ajax.onreadystatechange = function() {
            if (ajax.readyState != 4 || ajax.status != 200) {
                console.log('ajax error')
                return
            }
            console.log('ajax succeeded')
        }
        ajax.send({})
    }
</script>